const list = await (await fetch('http://127.0.0.1:9223/json/list')).json();
const page = list.find(t => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = () => rej(new Error('ws')) });
let id = 0; const pend = {};
ws.onmessage = ev => { const d = JSON.parse(ev.data); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id] } };
const send = (m, p = {}) => new Promise(res => { const i = ++id; pend[i] = res; ws.send(JSON.stringify({ id: i, method: m, params: p })) });
const expr = `(function(){
  var out={};
  out.scripts=[].map.call(document.querySelectorAll('script'),function(s){return s.src?s.src.split('/').slice(-1)[0]:'inline:'+s.textContent.slice(0,30)});
  out.links=[].map.call(document.querySelectorAll('link'),function(l){return l.href.split('/').slice(-1)[0]});
  out.hasBridge=typeof Bridge!=='undefined';
  out.hasEngine=typeof Engine!=='undefined';
  out.hasGsrc=typeof gSrc!=='undefined';
  out.docname=document.getElementById('docname')?document.getElementById('docname').value:'NO';
  out.tabDom=document.querySelectorAll('#filetabs .ftab').length;
  return out;
})()`;
const r = await send('Runtime.evaluate', { expression: expr, returnByValue: true });
console.log(JSON.stringify(r.result?.result?.value, null, 1));
ws.close(); process.exit(0);
