const list = await (await fetch('http://127.0.0.1:9223/json/list')).json();
const page = list.find(t => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = () => rej(new Error('ws')) });
let id = 0; const pend = {};
ws.onmessage = ev => { const d = JSON.parse(ev.data); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id] } };
const send = (m, p = {}) => new Promise(res => { const i = ++id; pend[i] = res; ws.send(JSON.stringify({ id: i, method: m, params: p })) });
const expr = `(function(){
  var out={};
  var x=new XMLHttpRequest();
  x.open('GET','index.html',false);
  x.send();
  var h=x.responseText;
  out.len=h.length;
  out.scriptTags=(h.match(/<script[^>]*src="[^"]*"/g)||[]);
  out.stateTag=h.indexOf('js/state.js')>=0;
  out.caretTag=h.indexOf('js/core/caret.js')>=0;
  out.mainTag=h.indexOf('js/main.js')>=0;
  var y=new XMLHttpRequest();
  y.open('GET','js/state.js',false);
  y.send();
  out.stateStatus=y.status;
  out.stateCT=y.getResponseHeader('content-type');
  return out;
})()`;
const r = await send('Runtime.evaluate', { expression: expr, returnByValue: true });
console.log(JSON.stringify(r.result?.result?.value, null, 1));
ws.close(); process.exit(0);
