const list = await (await fetch('http://127.0.0.1:9223/json/list')).json();
const page = list.find(t => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = () => rej(new Error('ws')) });
let id = 0; const pend = {};
ws.onmessage = ev => { const d = JSON.parse(ev.data); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id] } };
const send = (m, p = {}) => new Promise(res => { const i = ++id; pend[i] = res; ws.send(JSON.stringify({ id: i, method: m, params: p })) });
const expr = `(function(){
  var out={};
  out.scripts=[].map.call(document.querySelectorAll('script'),function(s){return s.src?s.src.split('/').slice(-1)[0]:'inline:'+s.textContent.slice(0,40)});
  out.hasBridge=typeof Bridge!=='undefined';
  out.hasEngine=typeof Engine!=='undefined';
  out.hasS=typeof S!=='undefined';
  out.stateErr=window.__stateErr||null;
  var x=new XMLHttpRequest();
  x.open('GET','js/state.js',false);
  x.send();
  out.stateStatus=x.status;
  out.stateCT=x.getResponseHeader('content-type');
  out.stateLen=x.responseText.length;
  var y=new XMLHttpRequest();
  y.open('GET','css/style.css',false);
  y.send();
  out.cssStatus=y.status;
  out.cssLen=y.responseText.length;
  return out;
})()`;
const r = await send('Runtime.evaluate', { expression: expr, returnByValue: true });
console.log(JSON.stringify(r.result?.result?.value, null, 1));
ws.close(); process.exit(0);
